### ISSUE TITLE
make search work for real

### ISSUE THREAD

**Issue by giogonzo** [sawsanias/gh-explorer#14]
## requirements

make this flow work "for real":
- user inputs a search string
- user clicks on "search"
- an api call to github is performed
- results are shown when available

The following sub issues should be approached in this order:
## subissues
- [x] link searchbox and results #13 
- [x] perform a dummy (hardcoded) search api call on github #18 
- [x] perform the correct search api call on github #19 
- [x] show error #20 
- [x] add autofocus, autoselect and onEnter to search bar #22
- [x] handle empty imput #23
- [x] navbar shouldn't shrink #27

**Comment by francescogior** [comment]
all done
