### ISSUE TITLE
[detail view] Create a detail view

### ISSUE THREAD

**Issue by francescogior** [sawsanias/gh-explorer#35]
## story
- as a user, I would like to be able to see more detail for each issue in the search results list
## requirements
- details shown on a modal
- modal should show up when the user click on a 'show detail' button, next to each repo
- data to be shown should be fetched from another call to github api to the single repo resource
## sub-issue
- [x] add 'show details' next to each repo in the list #36
- [x] add modal that shows up clicking on 'show details' button (import from brc) #37
- [x] fetch and show the relevant details in the modal #38 
- [ ] add loadingSpinner and error message inside the modal #42
